"""initial schema

Revision ID: 56af2791774f
Revises:
Create Date: 2026-07-20 11:09:52.361402

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "56af2791774f"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organizations",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("billing_plan", sa.String(length=50), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_orgs_name", "organizations", ["name"], unique=True)
    op.create_table(
        "outbox_events",
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column("aggregate_type", sa.String(length=50), nullable=False),
        sa.Column("aggregate_id", sa.String(length=36), nullable=False),
        sa.Column("correlation_id", sa.String(length=36), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("published", sa.Boolean(), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_outbox_created", "outbox_events", ["created_at"], unique=False)
    op.create_index("ix_outbox_published", "outbox_events", ["published"], unique=False)
    op.create_table(
        "prompt_templates",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("template_text", sa.Text(), nullable=False),
        sa.Column("system_prompt", sa.Text(), nullable=True),
        sa.Column(
            "default_provider",
            sa.Enum("ANTHROPIC", "OPENAI", "GOOGLE", "LOCAL", name="model_provider"),
            nullable=False,
        ),
        sa.Column("default_model", sa.String(length=255), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_prompt_name", "prompt_templates", ["name"], unique=True)
    op.create_table(
        "repositories",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("owner", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=512), nullable=False),
        sa.Column("clone_url", sa.Text(), nullable=False),
        sa.Column("default_branch", sa.String(length=255), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PENDING", "IMPORTING", "READY", "FAILED", "ARCHIVED", name="repository_status"),
            nullable=False,
        ),
        sa.Column("commit_sha", sa.String(length=40), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("primary_language", sa.String(length=50), nullable=True),
        sa.Column("frameworks", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("total_files", sa.Integer(), nullable=False),
        sa.Column("total_size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("is_private", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_repositories_org", "repositories", ["organization_id"], unique=False)
    op.create_index("ix_repositories_owner_name", "repositories", ["owner", "name"], unique=True)
    op.create_index("ix_repositories_status", "repositories", ["status"], unique=False)
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_users_email", "users", ["email"], unique=True)
    op.create_table(
        "ast_cache_entries",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("repository_id", sa.Uuid(), nullable=False),
        sa.Column("checksum", sa.String(length=64), nullable=False),
        sa.Column("language", sa.String(length=50), nullable=False),
        sa.Column("parser_version", sa.String(length=50), nullable=False),
        sa.Column("ast_blob", sa.LargeBinary(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["repository_id"],
            ["repositories.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_ast_cache_checksum", "ast_cache_entries", ["repository_id", "checksum"], unique=True)
    op.create_index(
        "ix_ast_cache_repo_org",
        "ast_cache_entries",
        ["repository_id", "organization_id"],
        unique=False,
    )
    op.create_table(
        "import_jobs",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("repository_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "AUTHENTICATING",
                "CLONING",
                "SCANNING",
                "DETECTING",
                "BUILDING_MANIFEST",
                "PERSISTING",
                "COMPLETED",
                "FAILED",
                "CANCELLED",
                name="import_job_status",
            ),
            nullable=False,
        ),
        sa.Column("worker_id", sa.String(length=255), nullable=True),
        sa.Column("branch", sa.String(length=255), nullable=False),
        sa.Column("commit_sha", sa.String(length=40), nullable=True),
        sa.Column("retries", sa.Integer(), nullable=False),
        sa.Column("max_retries", sa.Integer(), nullable=False),
        sa.Column("duration_ms", sa.BigInteger(), nullable=True),
        sa.Column("error_code", sa.String(length=50), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["repository_id"],
            ["repositories.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_import_jobs_org", "import_jobs", ["organization_id"], unique=False)
    op.create_index("ix_import_jobs_repository_id", "import_jobs", ["repository_id"], unique=False)
    op.create_index("ix_import_jobs_status", "import_jobs", ["status"], unique=False)
    op.create_table(
        "indexing_jobs",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("repository_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "QUEUED",
                "SCANNING",
                "PARSING",
                "PERSISTING",
                "COMPLETED",
                "FAILED",
                name="indexing_status",
            ),
            nullable=False,
        ),
        sa.Column("commit_sha", sa.String(length=40), nullable=False),
        sa.Column("branch", sa.String(length=255), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["repository_id"],
            ["repositories.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_idx_jobs_repo_org", "indexing_jobs", ["repository_id", "organization_id"], unique=False)
    op.create_index("ix_idx_jobs_status", "indexing_jobs", ["status"], unique=False)
    op.create_table(
        "repository_files",
        sa.Column("repository_id", sa.Uuid(), nullable=False),
        sa.Column("relative_path", sa.Text(), nullable=False),
        sa.Column("file_name", sa.String(length=255), nullable=False),
        sa.Column("extension", sa.String(length=20), nullable=True),
        sa.Column("language", sa.String(length=50), nullable=True),
        sa.Column("category", sa.String(length=20), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("checksum", sa.String(length=64), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["repository_id"],
            ["repositories.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_repo_files_category", "repository_files", ["category"], unique=False)
    op.create_index("ix_repo_files_path", "repository_files", ["repository_id", "relative_path"], unique=True)
    op.create_index("ix_repo_files_repo_id", "repository_files", ["repository_id"], unique=False)
    op.create_table(
        "repository_languages",
        sa.Column("repository_id", sa.Uuid(), nullable=False),
        sa.Column("language", sa.String(length=50), nullable=False),
        sa.Column("file_count", sa.Integer(), nullable=False),
        sa.Column("byte_count", sa.Integer(), nullable=False),
        sa.Column("percentage", sa.Float(), nullable=False),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["repository_id"],
            ["repositories.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_repo_lang_repo_id", "repository_languages", ["repository_id"], unique=False)
    op.create_table(
        "repository_manifests",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("repository_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("manifest", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["repository_id"],
            ["repositories.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_manifests_org", "repository_manifests", ["organization_id"], unique=False)
    op.create_index(
        "ix_manifests_repo_version",
        "repository_manifests",
        ["repository_id", "version"],
        unique=True,
    )
    op.create_table(
        "repository_memory_versions",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("repository_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("commit_sha", sa.String(length=40), nullable=False),
        sa.Column("branch", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["repository_id"],
            ["repositories.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_repo_mem_versions_repo_org",
        "repository_memory_versions",
        ["repository_id", "organization_id"],
        unique=False,
    )
    op.create_index(
        "ix_repo_mem_versions_version",
        "repository_memory_versions",
        ["repository_id", "version"],
        unique=True,
    )
    op.create_table(
        "role_bindings",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("role", sa.String(length=50), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_role_bindings_org_user", "role_bindings", ["organization_id", "user_id"], unique=True)
    op.create_table(
        "indexing_failures",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("repository_id", sa.Uuid(), nullable=False),
        sa.Column("indexing_job_id", sa.Uuid(), nullable=False),
        sa.Column("file_path", sa.Text(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=False),
        sa.Column("traceback", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["indexing_job_id"],
            ["indexing_jobs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["repository_id"],
            ["repositories.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_idx_fails_file", "indexing_failures", ["file_path"], unique=False)
    op.create_index("ix_idx_fails_job", "indexing_failures", ["indexing_job_id"], unique=False)
    op.create_table(
        "plans",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("repository_id", sa.Uuid(), nullable=False),
        sa.Column("memory_version_id", sa.Uuid(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "PENDING_APPROVAL",
                "APPROVED",
                "REJECTED",
                "EXECUTING",
                "COMPLETED",
                "FAILED",
                "SUPERSEDED",
                name="plan_status",
            ),
            nullable=False,
        ),
        sa.Column("intent", sa.Text(), nullable=False),
        sa.Column("context_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["memory_version_id"],
            ["repository_memory_versions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["repository_id"],
            ["repositories.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_plans_repo_org", "plans", ["repository_id", "organization_id"], unique=False)
    op.create_index("ix_plans_status", "plans", ["status"], unique=False)
    op.create_table(
        "source_files",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("repository_id", sa.Uuid(), nullable=False),
        sa.Column("memory_version_id", sa.Uuid(), nullable=False),
        sa.Column("file_path", sa.Text(), nullable=False),
        sa.Column("checksum", sa.String(length=64), nullable=False),
        sa.Column("language", sa.String(length=50), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("lines", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["memory_version_id"],
            ["repository_memory_versions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["repository_id"],
            ["repositories.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_source_files_checksum", "source_files", ["repository_id", "checksum"], unique=False)
    op.create_index("ix_source_files_path", "source_files", ["repository_id", "file_path"], unique=False)
    op.create_index(
        "ix_source_files_repo_org",
        "source_files",
        ["repository_id", "organization_id"],
        unique=False,
    )
    op.create_table(
        "context_snapshots",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("repository_id", sa.Uuid(), nullable=False),
        sa.Column("plan_id", sa.Uuid(), nullable=True),
        sa.Column("assembled_prompt", sa.Text(), nullable=False),
        sa.Column("context_data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("tokens_estimated", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["plans.id"],
        ),
        sa.ForeignKeyConstraint(
            ["repository_id"],
            ["repositories.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_context_plan", "context_snapshots", ["plan_id"], unique=False)
    op.create_index(
        "ix_context_repo_org",
        "context_snapshots",
        ["repository_id", "organization_id"],
        unique=False,
    )
    op.create_table(
        "dependency_edges",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("repository_id", sa.Uuid(), nullable=False),
        sa.Column("from_file_id", sa.Uuid(), nullable=False),
        sa.Column("to_file_id", sa.Uuid(), nullable=True),
        sa.Column("import_statement", sa.Text(), nullable=False),
        sa.Column("is_external", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["from_file_id"],
            ["source_files.id"],
        ),
        sa.ForeignKeyConstraint(
            ["repository_id"],
            ["repositories.id"],
        ),
        sa.ForeignKeyConstraint(
            ["to_file_id"],
            ["source_files.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_deps_from", "dependency_edges", ["from_file_id"], unique=False)
    op.create_index("ix_deps_repo_org", "dependency_edges", ["repository_id", "organization_id"], unique=False)
    op.create_index("ix_deps_to", "dependency_edges", ["to_file_id"], unique=False)
    op.create_table(
        "execution_jobs",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("repository_id", sa.Uuid(), nullable=False),
        sa.Column("plan_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "QUEUED",
                "RUNNING",
                "VERIFYING",
                "COMPLETED",
                "FAILED",
                "CANCELLED",
                "ROLLBACK",
                name="execution_status",
            ),
            nullable=False,
        ),
        sa.Column("commit_sha_before", sa.String(length=40), nullable=False),
        sa.Column("commit_sha_after", sa.String(length=40), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["plans.id"],
        ),
        sa.ForeignKeyConstraint(
            ["repository_id"],
            ["repositories.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_exec_jobs_plan", "execution_jobs", ["plan_id"], unique=False)
    op.create_index(
        "ix_exec_jobs_repo_org",
        "execution_jobs",
        ["repository_id", "organization_id"],
        unique=False,
    )
    op.create_index("ix_exec_jobs_status", "execution_jobs", ["status"], unique=False)
    op.create_table(
        "symbols",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("repository_id", sa.Uuid(), nullable=False),
        sa.Column("source_file_id", sa.Uuid(), nullable=False),
        sa.Column("memory_version_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("qualname", sa.Text(), nullable=False),
        sa.Column("symbol_type", sa.String(length=50), nullable=False),
        sa.Column("line_start", sa.Integer(), nullable=False),
        sa.Column("line_end", sa.Integer(), nullable=False),
        sa.Column("snippet", sa.Text(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["memory_version_id"],
            ["repository_memory_versions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["repository_id"],
            ["repositories.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_file_id"],
            ["source_files.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_symbols_file", "symbols", ["source_file_id"], unique=False)
    op.create_index("ix_symbols_name", "symbols", ["repository_id", "name"], unique=False)
    op.create_index("ix_symbols_repo_org", "symbols", ["repository_id", "organization_id"], unique=False)
    op.create_index("ix_symbols_type", "symbols", ["repository_id", "symbol_type"], unique=False)
    op.create_table(
        "task_nodes",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("plan_id", sa.Uuid(), nullable=False),
        sa.Column("action_type", sa.String(length=100), nullable=False),
        sa.Column("target", sa.Text(), nullable=False),
        sa.Column("parameters", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["plans.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_task_nodes_plan_org", "task_nodes", ["plan_id", "organization_id"], unique=False)
    op.create_table(
        "agent_interactions",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("repository_id", sa.Uuid(), nullable=False),
        sa.Column("context_snapshot_id", sa.Uuid(), nullable=False),
        sa.Column(
            "provider",
            sa.Enum("ANTHROPIC", "OPENAI", "GOOGLE", "LOCAL", name="model_provider"),
            nullable=False,
        ),
        sa.Column("model", sa.String(length=255), nullable=False),
        sa.Column("response_text", sa.Text(), nullable=False),
        sa.Column("tool_calls", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("prompt_tokens", sa.Integer(), nullable=False),
        sa.Column("completion_tokens", sa.Integer(), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["context_snapshot_id"],
            ["context_snapshots.id"],
        ),
        sa.ForeignKeyConstraint(
            ["repository_id"],
            ["repositories.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_agent_repo_org",
        "agent_interactions",
        ["repository_id", "organization_id"],
        unique=False,
    )
    op.create_index("ix_agent_snapshot", "agent_interactions", ["context_snapshot_id"], unique=False)
    op.create_table(
        "call_edges",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("repository_id", sa.Uuid(), nullable=False),
        sa.Column("caller_symbol_id", sa.Uuid(), nullable=False),
        sa.Column("callee_symbol_id", sa.Uuid(), nullable=True),
        sa.Column("call_snippet", sa.Text(), nullable=False),
        sa.Column("line_start", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["callee_symbol_id"],
            ["symbols.id"],
        ),
        sa.ForeignKeyConstraint(
            ["caller_symbol_id"],
            ["symbols.id"],
        ),
        sa.ForeignKeyConstraint(
            ["repository_id"],
            ["repositories.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_calls_callee", "call_edges", ["callee_symbol_id"], unique=False)
    op.create_index("ix_calls_caller", "call_edges", ["caller_symbol_id"], unique=False)
    op.create_index("ix_calls_repo_org", "call_edges", ["repository_id", "organization_id"], unique=False)
    op.create_table(
        "execution_logs",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("execution_job_id", sa.Uuid(), nullable=False),
        sa.Column("task_node_id", sa.Uuid(), nullable=True),
        sa.Column("level", sa.String(length=20), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("stream", sa.String(length=20), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["execution_job_id"],
            ["execution_jobs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["task_node_id"],
            ["task_nodes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_exec_logs_job", "execution_logs", ["execution_job_id"], unique=False)
    op.create_index("ix_exec_logs_node", "execution_logs", ["task_node_id"], unique=False)
    op.create_table(
        "mutations",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("repository_id", sa.Uuid(), nullable=False),
        sa.Column("execution_job_id", sa.Uuid(), nullable=False),
        sa.Column("task_node_id", sa.Uuid(), nullable=False),
        sa.Column("file_path", sa.Text(), nullable=False),
        sa.Column("mutation_type", sa.String(length=50), nullable=False),
        sa.Column("diff_hunk", sa.Text(), nullable=False),
        sa.Column("is_reverted", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["execution_job_id"],
            ["execution_jobs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["repository_id"],
            ["repositories.id"],
        ),
        sa.ForeignKeyConstraint(
            ["task_node_id"],
            ["task_nodes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_mutations_job", "mutations", ["execution_job_id"], unique=False)
    op.create_index("ix_mutations_repo_org", "mutations", ["repository_id", "organization_id"], unique=False)
    op.create_table(
        "symbol_references",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("repository_id", sa.Uuid(), nullable=False),
        sa.Column("source_file_id", sa.Uuid(), nullable=False),
        sa.Column("symbol_id", sa.Uuid(), nullable=True),
        sa.Column("reference_name", sa.Text(), nullable=False),
        sa.Column("line_start", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["repository_id"],
            ["repositories.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_file_id"],
            ["source_files.id"],
        ),
        sa.ForeignKeyConstraint(
            ["symbol_id"],
            ["symbols.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_sym_refs_repo_org",
        "symbol_references",
        ["repository_id", "organization_id"],
        unique=False,
    )
    op.create_index("ix_sym_refs_symbol", "symbol_references", ["symbol_id"], unique=False)
    op.create_table(
        "task_edges",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("plan_id", sa.Uuid(), nullable=False),
        sa.Column("from_node_id", sa.Uuid(), nullable=False),
        sa.Column("to_node_id", sa.Uuid(), nullable=False),
        sa.Column("condition", sa.String(length=255), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["from_node_id"],
            ["task_nodes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["plans.id"],
        ),
        sa.ForeignKeyConstraint(
            ["to_node_id"],
            ["task_nodes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_task_edges_from", "task_edges", ["from_node_id"], unique=False)
    op.create_index("ix_task_edges_plan_org", "task_edges", ["plan_id", "organization_id"], unique=False)
    op.create_index("ix_task_edges_to", "task_edges", ["to_node_id"], unique=False)
    op.create_table(
        "verification_jobs",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("repository_id", sa.Uuid(), nullable=False),
        sa.Column("execution_job_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PENDING", "RUNNING", "PASSED", "FAILED", "ERROR", name="verification_status"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["execution_job_id"],
            ["execution_jobs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["repository_id"],
            ["repositories.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_verif_jobs_exec", "verification_jobs", ["execution_job_id"], unique=False)
    op.create_index(
        "ix_verif_jobs_repo_org",
        "verification_jobs",
        ["repository_id", "organization_id"],
        unique=False,
    )
    op.create_index("ix_verif_jobs_status", "verification_jobs", ["status"], unique=False)
    op.create_table(
        "repair_attempts",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("repository_id", sa.Uuid(), nullable=False),
        sa.Column("verification_job_id", sa.Uuid(), nullable=False),
        sa.Column("repair_execution_id", sa.Uuid(), nullable=False),
        sa.Column("prompt_used", sa.Text(), nullable=False),
        sa.Column("is_successful", sa.Boolean(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["repair_execution_id"],
            ["execution_jobs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["repository_id"],
            ["repositories.id"],
        ),
        sa.ForeignKeyConstraint(
            ["verification_job_id"],
            ["verification_jobs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_repair_repo_org", "repair_attempts", ["repository_id", "organization_id"], unique=False)
    op.create_index("ix_repair_verif", "repair_attempts", ["verification_job_id"], unique=False)
    op.create_table(
        "verification_results",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("verification_job_id", sa.Uuid(), nullable=False),
        sa.Column(
            "diagnostic_type",
            sa.Enum("LINT", "TYPE_CHECK", "UNIT_TEST", "BUILD", "SECURITY", name="diagnostic_type"),
            nullable=False,
        ),
        sa.Column("is_passed", sa.Boolean(), nullable=False),
        sa.Column("output", sa.Text(), nullable=False),
        sa.Column("parsed_diagnostics", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["verification_job_id"],
            ["verification_jobs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_verif_res_job", "verification_results", ["verification_job_id"], unique=False)
    op.create_index("ix_verif_res_type", "verification_results", ["diagnostic_type"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_verif_res_type", table_name="verification_results")
    op.drop_index("ix_verif_res_job", table_name="verification_results")
    op.drop_table("verification_results")
    op.drop_index("ix_repair_verif", table_name="repair_attempts")
    op.drop_index("ix_repair_repo_org", table_name="repair_attempts")
    op.drop_table("repair_attempts")
    op.drop_index("ix_verif_jobs_status", table_name="verification_jobs")
    op.drop_index("ix_verif_jobs_repo_org", table_name="verification_jobs")
    op.drop_index("ix_verif_jobs_exec", table_name="verification_jobs")
    op.drop_table("verification_jobs")
    op.drop_index("ix_task_edges_to", table_name="task_edges")
    op.drop_index("ix_task_edges_plan_org", table_name="task_edges")
    op.drop_index("ix_task_edges_from", table_name="task_edges")
    op.drop_table("task_edges")
    op.drop_index("ix_sym_refs_symbol", table_name="symbol_references")
    op.drop_index("ix_sym_refs_repo_org", table_name="symbol_references")
    op.drop_table("symbol_references")
    op.drop_index("ix_mutations_repo_org", table_name="mutations")
    op.drop_index("ix_mutations_job", table_name="mutations")
    op.drop_table("mutations")
    op.drop_index("ix_exec_logs_node", table_name="execution_logs")
    op.drop_index("ix_exec_logs_job", table_name="execution_logs")
    op.drop_table("execution_logs")
    op.drop_index("ix_calls_repo_org", table_name="call_edges")
    op.drop_index("ix_calls_caller", table_name="call_edges")
    op.drop_index("ix_calls_callee", table_name="call_edges")
    op.drop_table("call_edges")
    op.drop_index("ix_agent_snapshot", table_name="agent_interactions")
    op.drop_index("ix_agent_repo_org", table_name="agent_interactions")
    op.drop_table("agent_interactions")
    op.drop_index("ix_task_nodes_plan_org", table_name="task_nodes")
    op.drop_table("task_nodes")
    op.drop_index("ix_symbols_type", table_name="symbols")
    op.drop_index("ix_symbols_repo_org", table_name="symbols")
    op.drop_index("ix_symbols_name", table_name="symbols")
    op.drop_index("ix_symbols_file", table_name="symbols")
    op.drop_table("symbols")
    op.drop_index("ix_exec_jobs_status", table_name="execution_jobs")
    op.drop_index("ix_exec_jobs_repo_org", table_name="execution_jobs")
    op.drop_index("ix_exec_jobs_plan", table_name="execution_jobs")
    op.drop_table("execution_jobs")
    op.drop_index("ix_deps_to", table_name="dependency_edges")
    op.drop_index("ix_deps_repo_org", table_name="dependency_edges")
    op.drop_index("ix_deps_from", table_name="dependency_edges")
    op.drop_table("dependency_edges")
    op.drop_index("ix_context_repo_org", table_name="context_snapshots")
    op.drop_index("ix_context_plan", table_name="context_snapshots")
    op.drop_table("context_snapshots")
    op.drop_index("ix_source_files_repo_org", table_name="source_files")
    op.drop_index("ix_source_files_path", table_name="source_files")
    op.drop_index("ix_source_files_checksum", table_name="source_files")
    op.drop_table("source_files")
    op.drop_index("ix_plans_status", table_name="plans")
    op.drop_index("ix_plans_repo_org", table_name="plans")
    op.drop_table("plans")
    op.drop_index("ix_idx_fails_job", table_name="indexing_failures")
    op.drop_index("ix_idx_fails_file", table_name="indexing_failures")
    op.drop_table("indexing_failures")
    op.drop_index("ix_role_bindings_org_user", table_name="role_bindings")
    op.drop_table("role_bindings")
    op.drop_index("ix_repo_mem_versions_version", table_name="repository_memory_versions")
    op.drop_index("ix_repo_mem_versions_repo_org", table_name="repository_memory_versions")
    op.drop_table("repository_memory_versions")
    op.drop_index("ix_manifests_repo_version", table_name="repository_manifests")
    op.drop_index("ix_manifests_org", table_name="repository_manifests")
    op.drop_table("repository_manifests")
    op.drop_index("ix_repo_lang_repo_id", table_name="repository_languages")
    op.drop_table("repository_languages")
    op.drop_index("ix_repo_files_repo_id", table_name="repository_files")
    op.drop_index("ix_repo_files_path", table_name="repository_files")
    op.drop_index("ix_repo_files_category", table_name="repository_files")
    op.drop_table("repository_files")
    op.drop_index("ix_idx_jobs_status", table_name="indexing_jobs")
    op.drop_index("ix_idx_jobs_repo_org", table_name="indexing_jobs")
    op.drop_table("indexing_jobs")
    op.drop_index("ix_import_jobs_status", table_name="import_jobs")
    op.drop_index("ix_import_jobs_repository_id", table_name="import_jobs")
    op.drop_index("ix_import_jobs_org", table_name="import_jobs")
    op.drop_table("import_jobs")
    op.drop_index("ix_ast_cache_repo_org", table_name="ast_cache_entries")
    op.drop_index("ix_ast_cache_checksum", table_name="ast_cache_entries")
    op.drop_table("ast_cache_entries")
    op.drop_index("ix_users_email", table_name="users")
    op.drop_table("users")
    op.drop_index("ix_repositories_status", table_name="repositories")
    op.drop_index("ix_repositories_owner_name", table_name="repositories")
    op.drop_index("ix_repositories_org", table_name="repositories")
    op.drop_table("repositories")
    op.drop_index("ix_prompt_name", table_name="prompt_templates")
    op.drop_table("prompt_templates")
    op.drop_index("ix_outbox_published", table_name="outbox_events")
    op.drop_index("ix_outbox_created", table_name="outbox_events")
    op.drop_table("outbox_events")
    op.drop_index("ix_orgs_name", table_name="organizations")
    op.drop_table("organizations")
    # ### end Alembic commands ###
