"""Add event reliability models

Revision ID: ac3a21d5e8f0
Revises: d7b5578b4249
Create Date: 2026-07-20 17:13:26.378436

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ac3a21d5e8f0"
down_revision: str | None = "d7b5578b4249"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "processed_events",
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("consumer_name", sa.String(length=100), nullable=False),
        sa.Column("event_id", sa.String(length=36), nullable=False),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("result", sa.String(length=50), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "consumer_name", "event_id", name="uq_processed_event"),
    )
    op.create_index("ix_processed_event_org", "processed_events", ["organization_id"], unique=False)
    op.add_column("outbox_events", sa.Column("organization_id", sa.String(length=36), nullable=False))
    op.add_column("outbox_events", sa.Column("aggregate_version", sa.Integer(), nullable=False))
    op.add_column("outbox_events", sa.Column("causation_id", sa.String(length=36), nullable=True))
    op.add_column("outbox_events", sa.Column("schema_version", sa.String(length=10), nullable=False))
    op.add_column("outbox_events", sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False))
    op.drop_index(op.f("ix_outbox_created"), table_name="outbox_events")
    op.create_index("ix_outbox_occurred", "outbox_events", ["occurred_at"], unique=False)
    op.drop_column("outbox_events", "created_at")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "outbox_events",
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    )
    op.drop_index("ix_outbox_occurred", table_name="outbox_events")
    op.create_index(op.f("ix_outbox_created"), "outbox_events", ["created_at"], unique=False)
    op.drop_column("outbox_events", "occurred_at")
    op.drop_column("outbox_events", "schema_version")
    op.drop_column("outbox_events", "causation_id")
    op.drop_column("outbox_events", "aggregate_version")
    op.drop_column("outbox_events", "organization_id")
    op.drop_index("ix_processed_event_org", table_name="processed_events")
    op.drop_table("processed_events")
    # ### end Alembic commands ###
